use_frameworks!
platform :ios, '10.0'
target "Ellipse" do
       pod 'GoogleMaps', '~> 2.1.0'
       pod "FBSDKCoreKit"
       pod "FBSDKLoginKit"
       pod 'Google/CloudMessaging'
       pod 'SWTableViewCell', '~> 0.3.7'
       post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.2.0'
    end
  end
end
end 
